name: wishy_store
description: Graduation project

version: 1.0.0+1

environment:
  sdk: ">=2.12.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  animated_text_kit: ^4.2.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  fluttertoast: ^8.0.7
  cloud_firestore: ^4.0.2
  carousel_slider: ^4.1.1
  custom_navigation_bar: ^0.8.2
  settings_ui: ^2.0.2
#  firebase_analytics: ^9.1.1
  modal_progress_hud_nsn: ^0.3.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.2
  provider: ^6.0.2
  rflutter_alert: ^2.0.4
  dropdown_search: ^5.0.3
  flash: ^2.0.5
  image_picker: ^0.8.6
  firebase_storage: ^11.0.6
  eva_icons_flutter: ^3.1.0
  flutter_svg: ^1.1.6
  smooth_page_indicator: ^1.0.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/wishlistTypes/
    - images/Promotion/
    - images/storeCategories/
